### ISSUE TITLE
Cannot load /usr/share/rubygems-integration/all/specifications/bin/rake

### ISSUE THREAD

**Issue by xairy** [Shopify/mruby-engine#33]
Hi!

I'm getting the following error when trying to run `bin/rake spec`:

```
$ ./bin/rake spec
./bin/rake:16:in `load': cannot load such file -- /usr/share/rubygems-integration/all/specifications/bin/rake (LoadError)
	from ./bin/rake:16:in `<main>'
```

How do I fix this?

**Comment by xairy** [comment]
Fixed by:
```
sudo rm /usr/share/rubygems-integration/all/specifications/rake-10.5.0.gemspec
bundle install
```

**Comment by sjackman** [comment]
I was able to resolve this problem with
```sh
mkdir -p /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin
ln -s /usr/bin/rake /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/
```
https://github.com/Linuxbrew/brew/pull/477/commits/e5909f11b6de405d9a26191d154f1b650f6f8b41

**Comment by bitbd83** [comment]
Try: bundle update rake
It will solve this issue for sure.

**Comment by randomstability** [comment]
> I was able to resolve this problem with
> 
> ```shell
> mkdir -p /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin
> ln -s /usr/bin/rake /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/
> ```
> 
> [Linuxbrew/brew@e5909f1](https://github.com/Linuxbrew/brew/commit/e5909f11b6de405d9a26191d154f1b650f6f8b41)

This solved my issue for a newer version of rake on Ubuntu 18.04.  (I'm so lost)
